name: '发布到PlatformIO(自动)'
on:
  release:
    types: [published]

jobs:
  platformio-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt install -y unzip
          python3 -m pip -q install platformio
          python3 -m platformio account login -u ${{ secrets.PLATFORMIO_USERNAME }} -p ${{ secrets.PLATFORMIO_PASSWD }}
          version="${GITHUB_REF##*/}"
          wget -q -O openocd.zip "https://github.com/${{ github.repository }}/releases/download/${version}/openocd.zip"
          unzip openocd.zip -d openocd
      - name: publish
        run: |
          cd openocd
          python3 -m platformio pkg publish --type tool --notify  --non-interactive
